# Generated by Django 6.1.1 on 2026-10-09 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_avatar_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='approval_status',
            field=models.CharField(choices=[('approved', 'Approved'), ('pending', 'Pending approval'), ('rejected', 'Rejected')], db_index=True, default='approved', max_length=16),
        ),
    ]
