[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "s-bindipbuy", email = "newtoptec1@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "asgiref==3.12.1",
    "django-bolt>=0.11.1",
    "sqlparse==0.6.0",
    "whitenoise==6.12.0",
]
