import {
  AngularNodeAppEngine,
  createNodeRequestHandler,
  isMainModule,
  writeResponseToNodeResponse,
} from '@angular/ssr/node';
import express from 'express';
import http from 'node:http';
import { join } from 'node:path';

const BACKEND_URL = process.env['BACKEND_URL'] || 'http://127.0.0.1:8123';
const API_PREFIXES = [
  '/auth',
  '/bookings',
  '/core',
  '/notifications',
  '/owner/bookings',
  '/owner/payments',
  '/owner/properties',
  '/payments',
  '/properties',
  '/refunds',
  '/rent/bookings',
  '/rent/favorites',
  '/rent/payments',
  '/rent/properties',
  '/rent/property',
  '/users',
];

const browserDistFolder = join(import.meta.dirname, '../browser');

const app = express();
const angularApp = new AngularNodeAppEngine();

const backendTarget = new URL(BACKEND_URL);

const HOP_BY_HOP = new Set([
  'connection',
  'keep-alive',
  'proxy-authenticate',
  'proxy-authorization',
  'te',
  'trailer',
  'transfer-encoding',
  'upgrade',
]);

app.use((req, res, next) => {
  const isApiAlias = req.path === '/api' || req.path.startsWith('/api/');
  const isApi = API_PREFIXES.some(
    (prefix) => req.path === prefix || req.path.startsWith(`${prefix}/`),
  );
  if (!isApi && !isApiAlias) return next();

  const headers = { ...req.headers } as Record<string, string | string[] | undefined>;
  headers['host'] = backendTarget.host;
  for (const name of HOP_BY_HOP) delete headers[name];

  const proxyReq = http.request(
    {
      protocol: backendTarget.protocol,
      hostname: backendTarget.hostname,
      port: backendTarget.port || (backendTarget.protocol === 'https:' ? 443 : 80),
      method: req.method,
      path: isApiAlias ? req.originalUrl.replace(/^\/api(?=\/|$)/, '') : req.originalUrl,
      headers,
    },
    (proxyRes) => {
      res.status(proxyRes.statusCode || 502);
      for (const [name, value] of Object.entries(proxyRes.headers)) {
        if (!HOP_BY_HOP.has(name.toLowerCase()) && value !== undefined) {
          res.setHeader(name, value);
        }
      }
      proxyRes.pipe(res);
    },
  );
  proxyReq.on('error', (err) => {
    res.status(502).json({ detail: 'API backend unreachable', error: String(err.message) });
  });
  req.pipe(proxyReq);
});

/**
 * Example Express Rest API endpoints can be defined here.
 * Uncomment and define endpoints as necessary.
 *
 * Example:
 * ```ts
 * app.get('/api/{*splat}', (req, res) => {
 *   // Handle API request
 * });
 * ```
 */

/**
 * Serve static files from /browser
 */
app.use(
  express.static(browserDistFolder, {
    maxAge: '1y',
    index: false,
    redirect: false,
  }),
);

/**
 * Handle all other requests by rendering the Angular application.
 */
app.use((req, res, next) => {
  angularApp
    .handle(req)
    .then((response) =>
      response ? writeResponseToNodeResponse(response, res) : next(),
    )
    .catch(next);
});

/**
 * Start the server if this module is the main entry point, or it is ran via PM2.
 * The server listens on the port defined by the `PORT` environment variable, or defaults to 4000.
 */
if (isMainModule(import.meta.url) || process.env['pm_id']) {
  const port = process.env['PORT'] || 4000;
  app.listen(port, (error) => {
    if (error) {
      throw error;
    }

    console.log(`Node Express server listening on http://localhost:${port}`);
  });
}

/**
 * Request handler used by the Angular CLI (for dev-server and during build) or Firebase Cloud Functions.
 */
export const reqHandler = createNodeRequestHandler(app);

/**
 * Default export used by the SSR server bundle generated by `ng build`.
 */
export default app;
